ALTER TABLE tasks ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE project_pages ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE documents ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE document_folders ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE team_members ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE task_attachments ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE document_upload_reservations ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
